<a href="https://colab.research.google.com/github/Christina-178/DTS101_assignment-/blob/main/WEEK_6_Pandas_for_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NAME: CHRISTINA ABONGABY CHIBUMA
MATRIC NUMBER: UJ/2025/CP/0178


# WEEK 6: Pandas for Data Analysis

**Programme:** Data Science  
**Course Title:** Data Visualization and Storytelling (Practical)  
**Week:** 6  
**Contact Hours:** 2 Hours Lecture + 2 Hours Practical  

---

## 🎯 Objective

Learn how to use Pandas for structured data analysis.

Students will:

- Import Pandas
- Create DataFrames
- Read CSV files
- Explore datasets
- Compute statistics
- Filter data
- Perform basic analysis


# PART 1: Importing Pandas

Pandas is a powerful Python library used for data analysis.

In [84]:

import pandas as pd


If you get an error, install pandas using:

pip install pandas


# PART 2: Creating a DataFrame

A DataFrame is a table (rows and columns).

In [85]:

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Math": [65, 80, 45, 90, 75],
    "English": [70, 85, 50, 88, 80],
    "Science": [72, 78, 48, 92, 79]
}

df = pd.DataFrame(data)
df

      Name  Math  English  Science
0    Alice    65       70       72
1      Bob    80       85       78
2  Charlie    45       50       48
3    David    90       88       92
4      Eva    75       80       79


# PART 3: Exploring Data

In [86]:

df.head()

      Name  Math  English  Science
0    Alice    65       70       72
1      Bob    80       85       78
2  Charlie    45       50       48
3    David    90       88       92
4      Eva    75       80       79

In [87]:
df.tail(2)

    Name  Math  English  Science
3  David    90       88       92
4    Eva    75       80       79

In [88]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     5 non-null      object
 1   Math     5 non-null      int64
 2   English  5 non-null      int64
 3   Science  5 non-null      int64
dtypes: int64(3), object(1)
memory usage: 292.0+ bytes

In [89]:

df.describe()

            Math    English    Science
count   5.000000   5.000000   5.000000
mean   71.000000  74.600000  73.800000
std    17.102631  15.355781  16.161683
min    45.000000  50.000000  48.000000
25%    65.000000  70.000000  72.000000
50%    75.000000  80.000000  78.000000
75%    80.000000  85.000000  79.000000
max    90.000000  88.000000  92.000000


# PART 4: Selecting Columns

In [90]:

df["Math"]

0    65
1    80
2    45
3    90
4    75
Name: Math, dtype: int64

In [91]:

df[["Math", "English"]]

   Math  English
0    65       70
1    80       85
2    45       50
3    90       88
4    75       80

In [92]:
df["Name"]

0      Alice
1        Bob
2    Charlie
3      David
4        Eva
Name: Name, dtype: object

In [93]:
df[["Name", "Science"]]

      Name  Science
0    Alice       72
1      Bob       78
2  Charlie       48
3    David       92
4      Eva       79


# PART 5: Computing Averages

In [94]:

df["Math"].mean()

np.float64(71.0)

In [95]:

df[["Math", "English", "Science"]].mean()

Math       71.0
English    74.6
Science    73.8
dtype: float64

In [96]:
df[["Math", "English"]].mean()

Math       71.0
English    74.6
dtype: float64


# PART 6: Finding Maximum Values

In [97]:

df["Math"].max()

90

In [98]:

df[["English", "Math"]].max()

English    88
Math       90
dtype: int64

In [99]:
df["Science"].min()

48


# PART 7: Filtering Data

Example: Students who scored above 70 in Math

In [100]:

df[df["Math"] > 70]

    Name  Math  English  Science
1    Bob    80       85       78
3  David    90       88       92
4    Eva    75       80       79

In [101]:
df[df["Math"] > 80]

    Name  Math  English  Science
3  David    90       88       92

In [102]:
df[["Science", "English"]] < 70

   Science  English
0    False    False
1    False    False
2     True     True
3    False    False
4    False    False


# PART 8: Creating a New Column (Average Score)

In [103]:

df["Average"] = df[["Math", "English", "Science"]].mean(axis=1)
df

      Name  Math  English  Science    Average
0    Alice    65       70       72  69.000000
1      Bob    80       85       78  81.000000
2  Charlie    45       50       48  47.666667
3    David    90       88       92  90.000000
4      Eva    75       80       79  78.000000


# PART 9: Creating Pass/Fail Column

In [104]:

df["Result"] = df["Average"].apply(lambda x: "Pass" if x >= 50 else "Fail")
df

      Name  Math  English  Science    Average Result
0    Alice    65       70       72  69.000000   Pass
1      Bob    80       85       78  81.000000   Pass
2  Charlie    45       50       48  47.666667   Fail
3    David    90       88       92  90.000000   Pass
4      Eva    75       80       79  78.000000   Pass


# 🧪 PRACTICAL EXERCISE

1. Find the highest English score.
2. Find the lowest Science score.
3. Display students who scored below 60 in Math.
4. Compute overall class average (all subjects combined).
5. Add a Grade column:
   - 80+ = A
   - 70–79 = B
   - 60–69 = C
   - Below 60 = D

#1. Highest English Score

In [105]:
df["English"].max()

88

#2. Lowest Science Score

In [106]:
df["Science"].min()

48

#3. Students who scored below 60 in Math

In [107]:
df[df["Math"] < 60]

      Name  Math  English  Science    Average Result
2  Charlie    45       50       48  47.666667   Fail

#4. Overall Average

In [110]:
overall_average = df["Average"].mean()
print(overall_average)

73.13333333333333

#5. Grading

In [31]:
df["Grade"] = df["Average"].apply(lambda x: "A" if x >= 80
else "B" if x >= 70
else "C" if x >= 60
else "D"
)
df

      Name  Math  English  Science    Average Result Grade
0    Alice    65       70       72  69.000000   Pass     C
1      Bob    80       85       78  81.000000   Pass     A
2  Charlie    45       50       48  47.666667   Fail     D
3    David    90       88       92  90.000000   Pass     A
4      Eva    75       80       79  78.000000   Pass     B


# 📘 ASSIGNMENT (Week 6)

Using Pandas:

1. Create a new CSV file with at least 10 students.
2. Load the CSV using pd.read_csv().
3. Compute:
   - Subject averages
   - Overall student averages
4. Identify:
   - Top performing student
   - Lowest performing student
5. Export the updated dataset to a new CSV file.

Submit your completed notebook (.ipynb).

#1. Student file

In [121]:
import pandas as pd

In [123]:


data = {
"Name": ["Mikasa", "Eren", "Levi", "Armin", "Kenny", "Reiner", "Yemir", "Sasha", "Hange", "Zeke", "Conny", "Jean"],
"Math": [80, 96, 89, 90, 56, 70, 65, 89, 90, 45, 35, 78],
"English": [90, 80, 77, 86, 97, 67, 77, 56, 90, 78, 54, 64],
"Computer": [88, 90, 99, 76, 86, 90, 77, 98, 88, 99, 79, 91]
}
df = pd.DataFrame(data)

df.to_csv("Students.csv", index=False)

#2. Load the csv

In [128]:

df = pd.read_csv("Students.csv")
df

      Name  Math  English  Computer
0   Mikasa    80       90        88
1     Eren    96       80        90
2     Levi    89       77        99
3    Armin    90       86        76
4    Kenny    56       97        86
5   Reiner    70       67        90
6    Yemir    65       77        77
7    Sasha    89       56        98
8    Hange    90       90        88
9     Zeke    45       78        99
10   Conny    35       54        79
11    Jean    78       64        91

#3. Compute :
>Subject average
>Overall average

>Subject_averages

In [140]:
subject_averages = df[["Math", "English", "Computer"]].mean()
print("Average")
print(subject_averages)

Average
Math        73.583333
English     76.333333
Computer    88.416667
dtype: float64

>Overall_average

In [152]:
df["Average"] = df[["Math", "English", "Computer"]].mean(axis=1)
df

      Name  Math  English  Computer    Average
0   Mikasa    80       90        88  86.000000
1     Eren    96       80        90  88.666667
2     Levi    89       77        99  88.333333
3    Armin    90       86        76  84.000000
4    Kenny    56       97        86  79.666667
5   Reiner    70       67        90  75.666667
6    Yemir    65       77        77  73.000000
7    Sasha    89       56        98  81.000000
8    Hange    90       90        88  89.333333
9     Zeke    45       78        99  74.000000
10   Conny    35       54        79  56.000000
11    Jean    78       64        91  77.666667

In [153]:
overall_average = df["Average"].mean()
print("Overall Average", overall_average)

Overall Average 79.44444444444444

#4. Identify
>Top performing student

>Lowest performing student

>Top performing student

In [160]:
highest_avg = df["Average"].max()
top_student = df[df["Average"] == highest_avg]
print("Top performing student")
print(top_student)

Top performing student
    Name  Math  English  Computer    Average
8  Hange    90       90        88  89.333333

>Lowest performing student

In [161]:
lowest_avg = df["Average"].min()
lowest_student = df[df["Average"] == lowest_avg]
print("Lowest Performing student")
print(lowest_student)

Lowest Performing student
     Name  Math  English  Computer  Average
10  Conny    35       54        79     56.0

#5. Export the updated CSV

In [169]:
df.to_csv("Student_updated.csv")

In [165]:
import os
files = os.listdir()
print(files)

['.config', 'Students.csv', 'Students.CSV', 'Student_updated.csv', 'students.csv', 'sample_data']